# --- QSIM-QMIX parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the qsim_qmix_learner.py to train
agent_output_type: "q"
learner: "qsim_qmix_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

# QSIM specific parameters
ae_hidden_dim: 128
k_softmax: 3
similar_threshold: 0

name: "qsim_qmix"
